let mapleader = " "

syntax on
colorscheme habamax
set background=dark

set tabstop=4 softtabstop=4 shiftwidth=4
set scrolloff=10
set list listchars=tab:\:\ ,trail:·,extends:?,precedes:?,nbsp:×
" Indent guides: a │ at each indent level of leading spaces (matches shiftwidth=4)
let &listchars .= ',leadmultispace:│   '
set ai
set nowrap
set relativenumber
set ruler
set hlsearch
" Show [current/total] match count when searching
set shortmess-=S
set cursorline
set mouse=a

" Shift + H to go to the previous buffer
nnoremap <S-H> :bprevious<CR>

" Shift + L to go to the next buffer
nnoremap <S-L> :bnext<CR>

" Ctrl + H to go to the left window
nnoremap <C-H> <C-W>h

" Ctrl + L to go to the right window
nnoremap <C-L> <C-W>l

" Ctrl + K to go to the up window
nnoremap <C-K> <C-W>k

" Ctrl + J to go to the down window
nnoremap <C-J> <C-W>j

" Leader + e to toggle the file explorer (netrw); press again to return to the file
nnoremap <silent> <leader>e :execute &filetype ==# 'netrw' ? 'Rexplore' : 'Explore'<CR>
