alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
alias ls="eza"
alias l="ls -lah"
alias la="ls -lAh"
alias ll="ls -lh"
alias lsa="ls -lah"
alias lt="eza --tree --level=2 --long --icons --git"
alias ltree="eza --tree --level=2  --icons --git"
alias ta="tmux attach"
alias cat="bat"
alias yz="yazi"
alias vim="nvim"
alias c="clear && clear"
alias gs="git status -sb"
alias gds="git diff --staged"

alias md="mkdir -p"
alias rd="rmdir"
alias -- -="cd -"
alias -g ...="../.."
alias -g ....="../../.."
alias -g .....="../../../.."
alias -g ......="../../../../.."

alias grep="grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox,.venv,venv}"
alias egrep="grep -E"
alias fgrep="grep -F"
alias diff="diff --color"
