[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config]
lint = true
inlayHint.enable = true

[[language]]
name = "python"
scope ="source.python"
auto-format = false
indent = { tab-width = 4, unit = " " }
formatter = { command = "black", args = ["-", "-q"] }
roots = ["pyproject.toml", "pyrightconfig.json", "Poetry.lock"]
language-servers = [
    { name = "pyright" },
]
